SELECT ode.[pizza_id],month([date]) as month, year([date]) as year, --this will count the orders per month, and sum the quantity ordered for each pizza type
       COUNT(ord.[order_id]) AS number_of_orders_monthly,
       SUM(CAST(ode.[quantity] AS INT)) AS amount_of_quantity_ordered_monthly -- i cleaned the data from nvarchar to an integer so i can sum it
FROM [dbo].[orders] AS ord
INNER JOIN [dbo].[order_details] AS ode 
ON ord.order_id = ode.order_id
GROUP BY ode.[pizza_id],month([date]),year([date])
order by  SUM(CAST(ode.[quantity] AS INT)) desc 


select SUM([amount_of_quantity_ordered_monthly] * [price]) as monthly_sales,[month]---this gives total monthly sales 
FROM [dbo].[Pizzas_details] as P
inner join [dbo].[Order_3] as O
on P.pizza_id = O.pizza_id
Group by [month]


SELECT [name], [category], [ingredients], [pizza_type], [size], --this gives the monthly sales for each pizza type
       [month], [year], [number_of_orders_monthly], [amount_of_quantity_ordered_monthly],
       SUM([amount_of_quantity_ordered_monthly] * [price]) AS monthly_sales, P.[pizza_id] into #pizzasale
FROM [dbo].[Pizzas_details] AS P
INNER JOIN [dbo].[Order_3] AS O ON P.pizza_id = O.pizza_id
GROUP BY [name], [category], [ingredients], [pizza_type], [size], [month], 
    [year], [number_of_orders_monthly], [amount_of_quantity_ordered_monthly], P.[pizza_id]

select * from #pizzasale
where pizza_id= 'bbq_ckn_l'

SELECT [pizza_type], [year], SUM([monthly_sales]) as total_revenue_per_pizza --- Revenue generated by each pizza type at the end of the year
from #pizzasale
group by [pizza_type], [year]
order by SUM([monthly_sales]) desc


SELECT [size], [year], SUM([monthly_sales]) as total_revenue_per_pizza --- Revenue generated by each the different sizes of pizzas at the end of the year
from #pizzasale
group by [year], [size]
order by SUM([monthly_sales]) desc